{% set name = "data2rdf" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/data2rdf-{{ version }}.tar.gz
  sha256: c09bb611617ecd29ed0d72722da588456da79445c077d0d5c78309e0a34315a4
  patches:
    - cache.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - lru-cache <1
    - jsonpath-ng >=1.6.1,<1.7.dev0
    - pydantic >=2,<3
    - pydantic-settings
    - requests
    - python >={{ python_min }}
    - beautifulsoup4 >=4.0.0
    - chowlk-unofficial-fork ==0.0.2
    - openpyxl >=3,<4
    - pandas >=2,<3
    - python-dotenv
    - python-magic ==0.4.27
    - rdflib >=6,<7
    - pytables >=3,<4

test:
  imports:
    - data2rdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MI-FraunhoferIWM/data2rdf
  summary: A generic pipeline that can be used to map raw data to RDF.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
