{% set name = "data2rdf" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/data2rdf-{{ version }}.tar.gz
  sha256: f85919847782c54eb742327462943745a1c72e2a6b0698bdd0ba888e6f55233c

build:
  entry_points:
    - abox_conv = data2rdf.cli.abox_conversion:terminal
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - jsonpath-ng >=1.6.1,<1.7.dev0
    - backports.functools_lru_cache <1
    - pydantic >=2,<3
    - pydantic-settings
    - requests
    - python >=3.8
    - beautifulsoup4 >=4.0.0
    - chowlk-unofficial-fork ==0.0.2
    - openpyxl >=3,<4
    - pandas >=2,<3
    - python-dotenv
    - python-magic ==0.4.27
    - rdflib >=6,<7
    - pytables >=3,<4

test:
  imports:
    - data2rdf
  commands:
    - pip check
    - abox_conv --help
  requires:
    - pip

about:
  home: https://github.com/MI-FraunhoferIWM/data2rdf
  summary: A generic pipeline that can be used to map raw data to RDF.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
