{% set name = "data2rdf" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/data2rdf-{{ version }}.tar.gz
  sha256: 7611821833aae9c118435da5fdd10818b63d136ddcda7b9ccfe2ecfd91ceb945

build:
  entry_points:
    - abox_conv = data2rdf.cli.abox_conversion:terminal
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - beautifulsoup4 >=4.0.0
    - chowlk-unofficial-fork ==0.0.2
    - openpyxl >=3,<4
    - pandas >=2,<3
    - python-dotenv
    - python-magic ==0.4.27
    - rdflib ==6.2.0
    - pytables ==3.8.0

test:
  imports:
    - data2rdf
  commands:
    - pip check
    - abox_conv --help
  requires:
    - pip

about:
  home: https://github.com/MI-FraunhoferIWM/data2rdf
  summary: A generic pipeline that can be used to map raw data to RDF.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
